- name: Configure webserver with nginx and tls
  hosts: webservers
  sudo: True
#变量定义，后面template和copy的时候都会用到， index.html文件里的变量也会被替换。
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/site-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      yum: name=nginx update_cache=yes cache_valid_time=3600

    - name: create directories for ssl certificates
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS Key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configuration
      file: dest=/etc/nginx/site-enabled/default src={{ conf_file }} state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

#handler只会在上面的task改变了系统，才会通知handler进行执行下面的。
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

